CREATE TABLE ITEMS (
    ID INT NOT NULL,
    CONTENT TEXT ,
    STATUS CHAR(20) ,
    OWNER CHAR(200) ,
    CREATEDAT DATETIME ,
    UPDATEDAT DATETIME ,
    PRIMARY KEY ( ID )
);

CREATE TABLE USERS (
    ID INT NOT NULL,
    NAME CHAR(200) ,
    EMAIL CHAR(64) ,
    PASSWORD CHAR(64) ,
    CREATEDAT DATETIME ,
    PRIMARY KEY ( ID )
);